---

- name: Creates directory
  become: true
  file:
    path: /web
    state: directory

- name: Extract
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /web 

- name: Set Host Environment Variable
  become: true
  lineinfile:
    dest: /etc/environment
    line: "{{ item }}"
  loop:
    - "TYPEORM_CONNECTION=\"{{ lookup('env', 'TYPEORM_CONNECTION')}}\""
    - "TYPEORM_ENTITIES=\"{{ lookup('env', 'TYPEORM_ENTITIES')}}\""
    - "TYPEORM_HOST=\"{{ lookup('env', 'TYPEORM_HOST')}}\""
    - "TYPEORM_PORT=\"{{ lookup('env', 'TYPEORM_PORT')}}\""
    - "TYPEORM_USERNAME=\"{{ lookup('env', 'TYPEORM_USERNAME')}}\""
    - "TYPEORM_PASSWORD=\"{{ lookup('env', 'TYPEORM_PASSWORD')}}\""
    - "TYPEORM_DATABASE=\"{{ lookup('env', 'TYPEORM_DATABASE')}}\""
    - "TYPEORM_MIGRATIONS=\"{{ lookup('env', 'TYPEORM_MIGRATIONS')}}\""
    - "TYPEORM_MIGRATIONS_DIR=\"{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}\""   

- name: Executing node
  shell: |
    source /etc/environment
    cd web
    pm2 stop default
    pm2 start npm -- start
