---

- name: Creates directory
  become: true
  file:
    path: /web
    state: directory

- name: Extract
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /web 

- name: Create env file
  become: true
  copy:
    src: production.env
    dest: /web
    mode: '0777'

- name: Executing node
  become: true
  shell: |
    cd web
    pm2 stop default
    NODE_ENV=production pm2 start npm -- start
