---

- name: Creates directory
  become: true
  file:
    path: /web
    state: directory

- name: Extract
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /web

- name: Executing node
  become: true
  shell: |
    cd web
    pm2 stop default
    pm2 start npm -- start
