---

- name: Creates directory
  become: true
  file:
    path: /web
    state: directory

- name: Extract
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /web

- name: Set Host Environment Variable
  become: true
  lineinfile:
    dest: /etc/environment
    line: "{{ item }}"
  loop:
    - "TYPEORM_CONNECTION = $TYPEORM_CONNECTION"
    - "TYPEORM_ENTITIES = $TYPEORM_ENTITIES"
    - "TYPEORM_HOST = $TYPEORM_HOST"
    - "TYPEORM_PORT = $TYPEORM_PORT"
    - "TYPEORM_USERNAME = $TYPEORM_USERNAME"
    - "TYPEORM_PASSWORD = $TYPEORM_PASSWORD"
    - "TYPEORM_DATABASE = $TYPEORM_DATABASE"
    - "TYPEORM_MIGRATIONS = $TYPEORM_MIGRATIONS"
    - "TYPEORM_MIGRATIONS_DIR = $TYPEORM_MIGRATIONS_DIR"    

- name: Executing node
  become: true
  shell: |
    cd web
    pm2 stop default
    pm2 start npm -- start
